---
version: '2.1'

services:
  radiusd-tagged: &tagged
    image: jumanjiman/radiusd:${TAG}
    build:
      context: radiusd/
      labels:
        - org.label-schema.name=jumanjiman/radiusd
        - org.label-schema.description=FreeRadius server useful as a base image or to test other services
        - org.label-schema.url=https://github.com/jumanjihouse/docker-radius
        - org.label-schema.vcs-url=https://github.com/jumanjihouse/docker-radius.git
        - org.label-schema.docker.dockerfile=/radiusd/Dockerfile
        - org.label-schema.vcs-type=Git
        - org.label-schema.license=GPLv2
        - org.label-schema.build-date=${BUILD_DATE}
        - org.label-schema.vcs-ref=${VCS_REF}
        - org.label-schema.version=${VERSION}
        - org.label-schema.ci-build-url=${CI_BUILD_URL}

  radiusd-latest:
    <<: *tagged
    image: jumanjiman/radiusd

  radclient-tagged: &radclient-tagged
    image: jumanjiman/radclient:${TAG}
    build:
      context: radclient/
      labels:
        - org.label-schema.name=jumanjiman/radclient
        - org.label-schema.description=FreeRadius client useful as a base image or to test other services
        - org.label-schema.url=https://github.com/jumanjihouse/docker-radius
        - org.label-schema.vcs-url=https://github.com/jumanjihouse/docker-radius.git
        - org.label-schema.docker.dockerfile=/radclient/Dockerfile
        - org.label-schema.vcs-type=Git
        - org.label-schema.license=GPLv2
        - org.label-schema.build-date=${BUILD_DATE}
        - org.label-schema.vcs-ref=${VCS_REF}
        - org.label-schema.version=${VERSION}
        - org.label-schema.ci-build-url=${CI_BUILD_URL}

  radclient-latest:
    <<: *radclient-tagged
    image: jumanjiman/radclient
