#!/bin/sh
set -e

cat > ci/vars <<EOF
  VERSION=3.0.13-r2
  BUILD_DATE=$(date +%Y%m%dT%H%M)
  VCS_REF=${CIRCLE_SHA1:0:7}
  TAG=\${VERSION}-\${BUILD_DATE}-git-\${VCS_REF}

  export VERSION
  export BUILD_DATE
  export VCS_REF
  export TAG
EOF

. ci/vars

ci/clean

# Build app images that are used only for the test harness.
docker-compose build radclient

# Build the app images.
docker-compose build radiusd

# Show image sizes.
docker images | grep -e SIZE -e radiusd -e radclient
