#!/bin/sh
set -e
set -u

. ci/functions.sh
verbosity=1

cat > ci/vars <<EOF
  VERSION=3.0.13-r2
  BUILD_DATE=$(date +%Y%m%dT%H%M)
  VCS_REF=$(git describe --abbrev=7 --tags --always)
  TAG=\${VERSION}-\${BUILD_DATE}-git-\${VCS_REF}

  export VERSION
  export BUILD_DATE
  export VCS_REF
  export TAG
EOF

. ci/vars

echo
echo Clean up from previous runs.
ci/clean

echo
echo Build app images that are used only for the test harness.
docker-compose build radclient

echo
echo Build the app images.
docker-compose build radiusd

echo
echo Show image sizes.
docker images | grep -e SIZE -e radiusd -e radclient
