#!/bin/bash
set -eEu
set -o pipefail

. ci/functions.sh

echo
echo Clean up from previous runs.
ci/clean

echo
echo Build app images that are used only for the test harness.
docker-compose build radclient

echo
echo Build the app images.
docker-compose build radiusd

echo
echo Show image sizes.
docker images | grep -e SIZE -e radiusd -e radclient
