#!/bin/bash
set -e
set -u

(
docker rm -f radiusd.service || :
docker rmi jumanjiman/radiusd || :
docker rmi jumanjiman/radclient || :
docker images -q -f dangling=true | xargs docker rmi || :
) &> /dev/null
