#!/bin/bash
set -eEu
set -o pipefail

. ci/functions.sh

. ci/vars

# shellcheck disable=SC2154
docker login -u "${user}" -p "${pass}"
docker-compose -f docker-compose-metadata.yaml push
docker logout

# Ask microbadger to update.
echo -n 'INFO: ask microbadger to check radclient'
curl -X POST 'https://hooks.microbadger.com/images/jumanjiman/radclient/-1Fk38Q1-DHDKIA9DNpLJcYvt54='
echo
echo -n 'INFO: ask microbadger to check radiusd'
curl -X POST 'https://hooks.microbadger.com/images/jumanjiman/radiusd/fi2LOJtwgnKBG4ckSoQAvT3QBkY='
echo
