#!/bin/bash
set -eEu
set -o pipefail

. ci/bootstrap
. ci/functions.sh

echo
echo Start radiusd.
docker-compose up -d radiusd

echo
echo Invoke BATS tests.
echo
bats ci/test_*.bats

echo
echo Run file checks.
pre-commit run --all-files --verbose
